/*
 * Nocturne - by Mudassir
 * Licensed Under GPL-3.0
 */

package com.mudassir131.yt.playback.enhancement.model

import androidx.annotation.FloatRange
import kotlin.math.max
import kotlin.math.min

/**
 * Compact numerical audio characteristics extracted locally from PCM audio.
 * Sent to the AI optimizer instead of raw audio.
 */
data class AudioCharacteristics(
    val rmsDb: Float = -24.0f,
    val peakDb: Float = -1.0f,
    val crestFactorDb: Float = 12.0f,
    val dynamicRangeDb: Float = 20.0f,
    val spectralCentroidHz: Float = 2500.0f,
    val spectralRolloffHz: Float = 12000.0f,
    val spectralFlux: Float = 0.5f,
    val subBassEnergy: Float = 0.15f,     // 20-60 Hz
    val bassEnergy: Float = 0.25f,        // 60-250 Hz
    val lowMidEnergy: Float = 0.20f,      // 250-500 Hz
    val midEnergy: Float = 0.20f,         // 500-2000 Hz
    val presenceEnergy: Float = 0.12f,    // 2000-6000 Hz
    val highEnergy: Float = 0.08f,        // 6000-20000 Hz
    val airEnergy: Float = 0.03f,         // 10000-20000 Hz
    val estimatedClipping: Float = 0.0f,  // 0.0 (clean) to 1.0 (heavily clipped)
    val estimatedCompression: Float = 0.5f,// 0.0 (very dynamic) to 1.0 (over-compressed/brickwalled)
    val transientDensity: Float = 2.5f,   // Transients / second
    val sampleRate: Int = 44100,
    val channelCount: Int = 2,
)

/**
 * Enhancement modes supported by Nocturne.
 */
enum class EnhancementMode(val displayName: String, val description: String) {
    NATURAL(
        "Natural",
        "Transparent, gentle cleanup preserving exact original acoustic balance",
    ),
    CLEAR(
        "Clear",
        "Focused vocal presence and low-mid de-mudding for articulate lyrics and instruments",
    ),
    DETAILED(
        "Detailed",
        "Micro-dynamic enhancement, transient definition, and airy high-frequency extension",
    ),
    HI_RES_FEEL(
        "Hi-Res Feel",
        "Flagship profile: rich definition, controlled dynamic sub-bass, harmonic depth, and spatial separation",
    ),
    STUDIO(
        "Studio",
        "Mastering-grade tonal balance, transparent dynamics control, and broadcast true-peak limiting",
    ),
    CUSTOM(
        "Custom",
        "User fine-tuned parametric DSP parameters",
    ),
}

/**
 * Status of the AI Audio Enhancement engine for UI display and diagnostics.
 */
enum class EnhancementStatus(val label: String) {
    DISABLED("Disabled"),
    ANALYZING("Analyzing Audio..."),
    OPTIMIZING("AI Optimizing..."),
    AI_OPTIMIZED("AI Profile Active"),
    CACHED("Using Cached Profile"),
    LOCAL_ACTIVE("Local DSP Active"),
    ADAPTING("Live Adapting"),
    ERROR("AI Unavailable — Local DSP Active"),
}

/**
 * Supported AI Providers for Bring-Your-Own-Key.
 */
enum class AiProviderType(val displayName: String) {
    GOOGLE_GEMINI("Google Gemini (Recommended)"),
    OPENAI_COMPATIBLE("OpenAI / Compatible"),
    LOCAL_ONLY("Local Only (No Network)"),
}

/**
 * Origin of the active enhancement profile.
 */
enum class ProfileSource {
    AI_OPTIMIZED,
    CACHED,
    LOCAL_FALLBACK,
    PRESET_DEFAULT,
    USER_CUSTOM,
}

/**
 * Structured DSP parameters returned by the AI or generated by local fallback.
 * Every field has strict minimum/maximum bounds and finite number validation.
 */
data class EnhancementProfile(
    @FloatRange(from = -12.0, to = 0.0)
    val preampDb: Float = -2.0f,

    @FloatRange(from = -6.0, to = 6.0)
    val lowShelfDb: Float = 1.5f,

    @FloatRange(from = -6.0, to = 3.0)
    val lowMidDb: Float = -0.8f,

    @FloatRange(from = -3.0, to = 5.0)
    val presenceDb: Float = 1.0f,

    @FloatRange(from = -4.0, to = 5.0)
    val airDb: Float = 1.2f,

    @FloatRange(from = 0.0, to = 1.0)
    val bassDynamicAmount: Float = 0.25f,

    @FloatRange(from = 0.0, to = 1.0)
    val compressionAmount: Float = 0.15f,

    @FloatRange(from = 0.0, to = 0.3)
    val harmonicAmount: Float = 0.08f,

    @FloatRange(from = 0.0, to = 0.3)
    val stereoAmount: Float = 0.05f,

    @FloatRange(from = -3.0, to = -0.1)
    val limiterCeilingDb: Float = -1.0f,

    @FloatRange(from = 0.0, to = 1.0)
    val confidence: Float = 1.0f,

    val mode: EnhancementMode = EnhancementMode.HI_RES_FEEL,
    val source: ProfileSource = ProfileSource.PRESET_DEFAULT,
    val timestampMs: Long = System.currentTimeMillis(),
) {
    /**
     * Clamps all parameters strictly to safe, non-destructive boundaries
     * and guarantees no NaN or Infinite floats ever reach the DSP audio engine.
     */
    fun sanitize(): EnhancementProfile {
        fun safeFloat(v: Float, minV: Float, maxV: Float, defaultV: Float): Float {
            return if (v.isNaN() || v.isInfinite()) defaultV else v.coerceIn(minV, maxV)
        }

        val safeLowShelf = safeFloat(lowShelfDb, -6.0f, 6.0f, 0.0f)
        val safeLowMid = safeFloat(lowMidDb, -6.0f, 3.0f, 0.0f)
        val safePresence = safeFloat(presenceDb, -3.0f, 5.0f, 0.0f)
        val safeAir = safeFloat(airDb, -4.0f, 5.0f, 0.0f)

        // Calculate required headroom based on positive EQ boosts
        val maxEqBoost = max(0.0f, max(safeLowShelf, max(safeLowMid, max(safePresence, safeAir))))
        val dynamicHeadroom = safeFloat(bassDynamicAmount, 0.0f, 1.0f, 0.2f) * 0.5f
        val recommendedPreamp = -maxEqBoost - dynamicHeadroom - 0.5f

        val safePreamp = min(
            safeFloat(preampDb, -12.0f, 0.0f, -2.0f),
            recommendedPreamp.coerceIn(-12.0f, 0.0f)
        )

        return copy(
            preampDb = safePreamp,
            lowShelfDb = safeLowShelf,
            lowMidDb = safeLowMid,
            presenceDb = safePresence,
            airDb = safeAir,
            bassDynamicAmount = safeFloat(bassDynamicAmount, 0.0f, 1.0f, 0.2f),
            compressionAmount = safeFloat(compressionAmount, 0.0f, 1.0f, 0.15f),
            harmonicAmount = safeFloat(harmonicAmount, 0.0f, 0.30f, 0.05f),
            stereoAmount = safeFloat(stereoAmount, 0.0f, 0.30f, 0.05f),
            limiterCeilingDb = safeFloat(limiterCeilingDb, -3.0f, -0.1f, -1.0f),
            confidence = safeFloat(confidence, 0.0f, 1.0f, 0.9f),
        )
    }

    companion object {
        const val DSP_ALGORITHM_VERSION = 2

        val DEFAULT_SAFE = EnhancementProfile(
            preampDb = -2.0f,
            lowShelfDb = 1.0f,
            lowMidDb = -0.5f,
            presenceDb = 0.8f,
            airDb = 1.0f,
            bassDynamicAmount = 0.20f,
            compressionAmount = 0.10f,
            harmonicAmount = 0.05f,
            stereoAmount = 0.04f,
            limiterCeilingDb = -1.0f,
            confidence = 1.0f,
            mode = EnhancementMode.HI_RES_FEEL,
            source = ProfileSource.PRESET_DEFAULT,
        )

        fun forMode(mode: EnhancementMode): EnhancementProfile {
            return when (mode) {
                EnhancementMode.NATURAL -> EnhancementProfile(
                    preampDb = -1.0f,
                    lowShelfDb = 0.5f,
                    lowMidDb = -0.3f,
                    presenceDb = 0.4f,
                    airDb = 0.5f,
                    bassDynamicAmount = 0.15f,
                    compressionAmount = 0.05f,
                    harmonicAmount = 0.02f,
                    stereoAmount = 0.02f,
                    limiterCeilingDb = -1.0f,
                    mode = mode,
                    source = ProfileSource.PRESET_DEFAULT,
                )
                EnhancementMode.CLEAR -> EnhancementProfile(
                    preampDb = -2.0f,
                    lowShelfDb = 0.5f,
                    lowMidDb = -1.5f,
                    presenceDb = 2.2f,
                    airDb = 1.5f,
                    bassDynamicAmount = 0.25f,
                    compressionAmount = 0.15f,
                    harmonicAmount = 0.04f,
                    stereoAmount = 0.04f,
                    limiterCeilingDb = -1.0f,
                    mode = mode,
                    source = ProfileSource.PRESET_DEFAULT,
                )
                EnhancementMode.DETAILED -> EnhancementProfile(
                    preampDb = -2.5f,
                    lowShelfDb = 1.2f,
                    lowMidDb = -0.8f,
                    presenceDb = 1.5f,
                    airDb = 2.5f,
                    bassDynamicAmount = 0.25f,
                    compressionAmount = 0.12f,
                    harmonicAmount = 0.08f,
                    stereoAmount = 0.08f,
                    limiterCeilingDb = -1.0f,
                    mode = mode,
                    source = ProfileSource.PRESET_DEFAULT,
                )
                EnhancementMode.HI_RES_FEEL -> DEFAULT_SAFE.copy(mode = mode)
                EnhancementMode.STUDIO -> EnhancementProfile(
                    preampDb = -2.0f,
                    lowShelfDb = 0.8f,
                    lowMidDb = -0.6f,
                    presenceDb = 1.0f,
                    airDb = 1.2f,
                    bassDynamicAmount = 0.35f,
                    compressionAmount = 0.25f,
                    harmonicAmount = 0.03f,
                    stereoAmount = 0.03f,
                    limiterCeilingDb = -1.0f,
                    mode = mode,
                    source = ProfileSource.PRESET_DEFAULT,
                )
                EnhancementMode.CUSTOM -> DEFAULT_SAFE.copy(mode = mode, source = ProfileSource.USER_CUSTOM)
            }
        }
    }
}

/**
 * State exposed to UI for real-time status and diagnostics.
 */
data class EnhancementState(
    val enabled: Boolean = false,
    val mode: EnhancementMode = EnhancementMode.HI_RES_FEEL,
    val status: EnhancementStatus = EnhancementStatus.DISABLED,
    val provider: AiProviderType = AiProviderType.GOOGLE_GEMINI,
    val activeProfile: EnhancementProfile = EnhancementProfile.DEFAULT_SAFE,
    val latestCharacteristics: AudioCharacteristics? = null,
    val currentTrackTitle: String = "",
    val isApiKeyConfigured: Boolean = false,
    val statusMessage: String = "Enhancement disabled",
)
